DROP TABLE if exists fire_incident;
CREATE TABLE fire_incident (
	incident_number DECIMAL NOT NULL, 
	exposure_number DECIMAL NOT NULL, 
	id DECIMAL NOT NULL, 
	address VARCHAR, 
	incident_date TIMESTAMP, 
	call_number DECIMAL, 
	alarm_dttm TIMESTAMP, 
	arrival_dttm TIMESTAMP, 
	close_dttm TIMESTAMP, 
	city VARCHAR, 
	zipcode VARCHAR, 
	battalion VARCHAR, 
	station_area VARCHAR, 
	box VARCHAR, 
	suppression_units DECIMAL, 
	suppression_personnel DECIMAL, 
	ems_units DECIMAL, 
	ems_personnel DECIMAL, 
	other_units DECIMAL, 
	other_personnel DECIMAL, 
	first_unit_on_scene VARCHAR, 
	estimated_property_loss DECIMAL, 
	estimated_contents_loss DECIMAL, 
	fire_fatalities DECIMAL, 
	fire_injuries DECIMAL, 
	civilian_fatalities DECIMAL, 
	civilian_injuries DECIMAL, 
	number_of_alarms DECIMAL, 
	primary_situation VARCHAR, 
	mutual_aid VARCHAR, 
	action_taken_primary VARCHAR, 
	action_taken_secondary VARCHAR, 
	action_taken_other VARCHAR, 
	detector_alerted_occupants VARCHAR, 
	property_use VARCHAR, 
	area_of_fire_origin VARCHAR, 
	ignition_cause VARCHAR, 
	ignition_factor_primary VARCHAR, 
	ignition_factor_secondary VARCHAR, 
	heat_source VARCHAR, 
	item_first_ignited VARCHAR, 
	human_factors_associated_with_ignition VARCHAR, 
	structure_type VARCHAR, 
	structure_status VARCHAR, 
	floor_of_fire_origin DECIMAL, 
	fire_spread VARCHAR, 
	no_flame_spead VARCHAR, 
	number_of_floors_with_minimum_damage DECIMAL, 
	number_of_floors_with_significant_damage DECIMAL, 
	number_of_floors_with_heavy_damage DECIMAL, 
	number_of_floors_with_extreme_damage DECIMAL, 
	detectors_present VARCHAR, 
	detector_type VARCHAR, 
	detector_operation VARCHAR, 
	detector_effectiveness VARCHAR, 
	detector_failure_reason VARCHAR, 
	automatic_extinguishing_system_present VARCHAR, 
	automatic_extinguishing_sytem_type VARCHAR, 
	automatic_extinguishing_sytem_perfomance VARCHAR, 
	automatic_extinguishing_sytem_failure_reason VARCHAR, 
	number_of_sprinkler_heads_operating DECIMAL, 
	supervisor_district DECIMAL, 
	neighborhood_district VARCHAR, 
	point VARCHAR
);

\COPY fire_incident (incident_number, exposure_number, id, address, incident_date, call_number, alarm_dttm, arrival_dttm, close_dttm, city, zipcode, battalion, station_area, box, suppression_units, suppression_personnel, ems_units, ems_personnel, other_units, other_personnel, first_unit_on_scene, estimated_property_loss, estimated_contents_loss, fire_fatalities, fire_injuries, civilian_fatalities, civilian_injuries, number_of_alarms, primary_situation, mutual_aid, action_taken_primary, action_taken_secondary, action_taken_other, detector_alerted_occupants, property_use, area_of_fire_origin, ignition_cause, ignition_factor_primary, ignition_factor_secondary, heat_source, item_first_ignited, human_factors_associated_with_ignition, structure_type, structure_status, floor_of_fire_origin, fire_spread, no_flame_spead, number_of_floors_with_minimum_damage, number_of_floors_with_significant_damage, number_of_floors_with_heavy_damage, number_of_floors_with_extreme_damage, detectors_present, detector_type, detector_operation, detector_effectiveness, detector_failure_reason, automatic_extinguishing_system_present, automatic_extinguishing_sytem_type, automatic_extinguishing_sytem_perfomance, automatic_extinguishing_sytem_failure_reason, number_of_sprinkler_heads_operating, supervisor_district, neighborhood_district, point) FROM '/home/austin/biToolTesting/fire_incidents.csv' WITH CSV DELIMITER ',' QUOTE '"' HEADER ;

--if postgis exists
